### ISSUE TITLE
Error entering alpine toolobx on pop_OS

### ISSUE THREAD

**Issue by spencergilbert** [lopukhov/unbox#9]
```shell
unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ unbox create -e podman -i docker.io/alpine:latest alpine

unbox on  main is 📦 v0.2.0 via 🦀 v1.63.0 
❯ unbox enter alpine
Error: 
   0: Could not spawn the requested command
   1: No such file or directory (os error 2)
```

As always, happy to help and contribute!

**Comment by lopukhov** [comment]
Thank you!

This happens because alpine does not have `bash` preinstalled. It should be an easy fix of trying `/bin/sh` if `$SHELL` fails. In the future I would like the preferred shell for each image be configurable at creation time such that this is fixed by:

```
unbox create alpine -e podman -i docker.io/alpine:latest -s /bin/sh
```

If you want to open a PR I will happily accept it. :smile:

**Comment by spencergilbert** [comment]
Ah, that seems obvious in hindsight now that you mention it. I'll see if I can find a bit of time to either a fallback shell, or perhaps bubbling up in the error that `bash` couldn't be found.
